version: '3'
services:
  redis:
    restart: always
    image: redis:4
    container_name: redis
    ports:
      - "6379:6379/tcp"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./data:/data
    command: redis-server --requirepass "123456" --save 60 1
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 512M
